{% set version = "1.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-spacyr
  version: {{ version|replace("-", "_") }}

source:
  fn: spacyr_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/spacyr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/spacyr/spacyr_{{ version }}.tar.gz
  sha256: e085a8e127e0a1df21543ed82ee18c507f3d94760f400280591d81ac89646e0b

build:
  noarch: generic
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
    - r-data.table
    - r-reticulate >=1.6

  run:
    - r-base
    - r-data.table
    - r-reticulate >=1.6

test:
  commands:
    - $R -e "library('spacyr')"           # [not win]
    - "\"%R%\" -e \"library('spacyr')\""  # [win]

about:
  home: http://github.com/quanteda/spacyr
  license: GPL-3
  summary: An R wrapper to the 'Python' 'spaCy' 'NLP' library, from <http://spacy.io>.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - stevierene82
