{% set version = '1.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-spacyr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/spacyr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/spacyr/spacyr_{{ version }}.tar.gz
  sha256: e085a8e127e0a1df21543ed82ee18c507f3d94760f400280591d81ac89646e0b

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-data.table
    - r-reticulate >=1.6
  run:
    - r-base
    - r-data.table
    - r-reticulate >=1.6

test:
  commands:
    - $R -e "library('spacyr')"           # [not win]
    - "\"%R%\" -e \"library('spacyr')\""  # [win]

about:
  home: https://spacyr.quanteda.io
  license: GPL-3
  summary: An R wrapper to the 'Python' 'spaCy' 'NLP' library, from <http://spacy.io>.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - stevierene82

# Package: spacyr
# Type: Package
# Title: Wrapper to the 'spaCy' 'NLP' Library
# Version: 1.0
# Authors@R: c( person("Kenneth", "Benoit", email = "kbenoit@lse.ac.uk", role = c("cre", "aut", "cph"), comment = c(ORCID = "0000-0002-0797-564X")),  person("Akitaka", "Matsuo", email = "a.matsuo@lse.ac.uk", role = "aut", comment = c(ORCID = "0000-0002-3323-6330")), person("European Research Council", role = "fnd", comment = "ERC-2011-StG 283794-QUANTESS") )
# Description: An R wrapper to the 'Python' 'spaCy' 'NLP' library, from <http://spacy.io>.
# License: GPL-3
# LazyData: TRUE
# Depends: R (>= 3.0.0), methods
# Imports: data.table, reticulate (>= 1.6)
# Suggests: knitr, quanteda, R.rsp, rmarkdown, spelling, testthat
# URL: https://spacyr.quanteda.io
# Encoding: UTF-8
# BugReports: https://github.com/quanteda/spacyr/issues
# RoxygenNote: 6.1.1
# Language: en-GB
# VignetteBuilder: R.rsp
# NeedsCompilation: no
# Packaged: 2018-12-15 07:16:36 UTC; kbenoit
# Author: Kenneth Benoit [cre, aut, cph] (<https://orcid.org/0000-0002-0797-564X>), Akitaka Matsuo [aut] (<https://orcid.org/0000-0002-3323-6330>), European Research Council [fnd] (ERC-2011-StG 283794-QUANTESS)
# Maintainer: Kenneth Benoit <kbenoit@lse.ac.uk>
# Repository: CRAN
# Date/Publication: 2018-12-15 07:40:03 UTC
