travis:
  secure:
    BINSTAR_TOKEN: ouHxvv7saeuCnIYfDfF87sX3V6MrAI8yrhu+5hrGzGzZjFkW1JwtnAh3mTfoLZMQr3OvMcG7gGx0JRZ+jPCmP47K+pm699a0fqV2jChxE0sSgcjVbWS7UctINBVpogkodtexjbFJDsf+c7V6PUqJEFa0LQqBD+aRNWIMqXiTL5lKcCSdCMpDvVtUEackqTmrACJU0w/eghVFnWcRJRMTThyNDoS7S/KWfM5pKAyXMZE9Vn/c1hNcCbPxej/1fUS8KAVS0M3BDEPbuS6BiMPPCHwrFBNN8FR8Kn/tUMU18HKVSJigbSTzRuW3Uwrd/Uj4pRgpml8qxMnd58lhUfX6OzgDZMji9rL4FxyzqPtaLXwJ2i061FMvrjo/ZXrmcWUGff/MgQuYd+tGPd+lcFmdhtnjvbXywnolkmrpEDWTrX/EIPkrGnO7x9pE5lZBibmbuqwBYmWh289Es7BvUD5eizj6Sx5l+VX5vI0co1Iugrhf1D47RLNLGvyKTGadludLItFu+c2VOolbTXT0Q89MyPXUkzT3ULFyX8EenNi5kJIxwjuSpgnW562YqkYm0PoQYtWGcem1Udwg+1hjBm3DffS61ELsn58VqMWRPIarJdzkPeZde6gbUVzygCGZ6cBmVNd8xeP1wErB61Ja6lxM8Hpu/7eLsPH3IReWSLXY13k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
